# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-5kcbBPbvSz1-VrC_Ob-Z7Cj_2DqeQZP
"""

x=5
print(f"變數x的值是: {x}")
print(f"變數x的記憶體地址是: {id(x)}")